name: 'Gradle Wrapper Cache'
description: 'Gradle Wrapper Cache'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
