spring:
  application:
    name: point-expiration-execution
  datasource:
    url: jdbc:postgresql://localhost:5432/wagokoro?currentSchema=point
    username: luster
    password: luster
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    configuration:
      minimum-idle: 10
      maximum-pool-size: 100
      read-only: false
      connection-init-sql: SELECT 1
  exposed:
    generate-ddl: false

logging:
  level:
    Exposed: debug
    jp:
      kukv: debug
